/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Ghost blocks",
  "description": "Shows a faint ghost of a block in its original position while dragging it.",
  "credits": [
    {
      "name": "supervoidcoder"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Ghost opacity (%)",
      "id": "opacity",
      "type": "integer",
      "min": 0,
      "max": 100,
      "default": 50
    }
  ],
  "dynamicDisable": true,
  "tags": ["recommended"],
  "enabledByDefault": false
};
export default manifest;