/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Red Bug Godzilla",
  "description": "A giant bug godzilla stomps through the editor every 2 minutes.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "tags": [
    "easterEgg"
  ],
  "enabledByDefault": false,
  "dynamicDisable": true
};
export default manifest;
