/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userstyle.css";
import _godzilla from "./red-bug-godzilla.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "red-bug-godzilla.svg": _godzilla,
};
