/* generated by pull.js */
const now = new Date();
const manifest = {
  "noTranslations": true,
  "name": "April Fools!",
  "description": "A fun April Fools addon featuring Red Bug Godzilla!",
  "credits": [
    {
      "name": "ampelc"
    }
  ],
  "userscripts": [
    {
      "url": "bug-godzilla.js"
    }
  ],
  "tags": [
    "theme",
    "new"
  ]
};

// Enable by default only on April 1st
// `Date` uses the system's local time zone, so this matches the user's local date.
const month = now.getMonth(); // April === 3 (0-based months)
const day = now.getDate();
manifest.enabledByDefault = (month === 3 && day === 1);

export default manifest;