/* generated by pull.js */
const manifest = {
  "name": "Broadcast tree",
  "description": "Shows a tree view of all blocks that send and receive a broadcast message when right-clicking on broadcast blocks.",
  "credits": [
    {
      "name": "supervoidcoder"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "tags": [
    "recommended"
  ],
  "enabledByDefault": true,
  "dynamicDisable": true,
  "editorOnly": true
};
export default manifest;
